---
title: 'data visualization #awesome'
author: "Jared Petry"
date: "2022-08-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = TRUE, warning = FALSE)
library(tidyverse) 
library(here) 
library(janitor) 

#cool graph libraries from gg__
library(patchwork)
library(ggrepel)
library(gghighlight) 
library(paletteer)
library(ggExtra) 
library(ggbeeswarm) 
library(gapminder) 
library(sf)

```

Read in the data 
```{r}
lizards <- read_csv(here::here("data_tidy", "lizards.csv"))
```

make some graphs 
```{r}
ggplot(data = lizards) +geom_line(aes(x = total_length, y = weight))
```

create historgram 
```{r}
ggplot(data = lizards, aes(x = total_length)) +
  geom_histogram(color = "orange", 
                 fill = "purple", 
                 size = 0.3, 
                 linetype = "dotted")

    #there are rules for determining the optimal number of bins for a given sample size that we'll learn later
```

```{r}
ggplot(data = lizards, aes(x = total_length, y = weight)) + 
  geom_point(shape = 22,       #shape of the dots 
             color = "cyan4",   #color of the dots' border
             fill = "yellow",   #color of the dot fill
             size = 4,      #size of the dots
             alpha = 0.4)  #transparency
```

map asthetics based on variables
```{r}
ggplot(data = lizards, aes(x = total_length, y = weight)) + 
  geom_point(aes(color = common_name,    #--- color is mapped based on common name
                 size = total_length,    #size of the dot is based on the total length 
                 ))
```

